AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  NewsApiKey:
    Type: String
    NoEcho: true
  SerpApiKey:
    Type: String
    NoEcho: true
  RetrievalApiBase:
    Type: String

Resources:
  DataCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.12
      Timeout: 60
      Environment:
        Variables:
          NEWSAPI_KEY: !Ref NewsApiKey
          SERP_API_KEY: !Ref SerpApiKey
          RETRIEVAL_API_BASE: !Ref RetrievalApiBase
      Events:
        DailyRefresh:
            Type: ScheduleV2
            Properties:
              ScheduleExpression: "rate(1 day)"
              Name: GhostieDailyRefresh
        ApiCatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiEndpoint:
    Description: "Your Swagger UI Docs Page"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/docs"
